# Generated by Django 5.2.3 on 2025-06-19 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('create_date', models.DateField()),
                ('photo', models.URLField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('number_of_likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('school', models.CharField(max_length=500)),
                ('schoolclass', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.AddField(
            model_name='idea',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.person'),
        ),
    ]
