# Generated by Django 5.2.3 on 2025-06-19 10:41

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_idea_person_delete_departments_delete_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='create_date',
            field=models.DateField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='idea',
            name='number_of_likes',
            field=models.IntegerField(db_default=0),
        ),
    ]
