# Generated by Django 5.2.3 on 2025-06-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_alter_idea_create_date_alter_idea_number_of_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
