# Generated by Django 5.2.3 on 2025-06-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_rename_owner_id_idea_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='photo',
            field=models.ImageField(upload_to='img'),
        ),
    ]
