# Generated by Django 5.2.3 on 2025-06-23 10:37

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_alter_idea_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='name',
            new_name='title',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_like', models.DateField(db_default=django.db.models.functions.datetime.Now())),
                ('idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.idea')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.person')),
            ],
        ),
    ]
