# Generated by Django 5.2.3 on 2025-06-25 12:56

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_rename_name_idea_title_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea_Deleted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('create_date', models.DateField(db_default=django.db.models.functions.datetime.Now())),
                ('photo', models.ImageField(upload_to='img')),
                ('status', models.CharField(max_length=500)),
                ('number_of_likes', models.IntegerField(db_default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmployeeApp.person')),
            ],
        ),
    ]
